const forecastConditions = [
  "Sol",
  "Céu limpo",
  "Parcialmente nublado",
  "Nublado",
  "Encoberto",
  "Neblina",
  "Possibilidade de chuva irregular",
  "Possibilidade de neve irregular",
  "Possibilidade de neve molhada irregular",
  "Possibilidade de chuvisco gelado irregular",
  "Rajadas de vento com neve",
  "Nevasca",
  "Nevoeiro",
  "Nevoeiro gelado",
  "Chuvisco irregular",
  "Chuvisco",
  "Chuvisco gelado",
  "Chuvisco forte gelado",
  "Chuva fraca irregular",
  "Chuva fraca",
  "Períodos de chuva moderada",
  "Chuva moderada",
  "Períodos de chuva forte",
  "Chuva forte",
  "Chuva fraca e gelada",
  "Chuva gelada moderada ou forte",
  "Chuva fraca com neve",
  "Chuva forte ou moderada com neve",
  "Queda de neve irregular e fraca",
  "Queda de neve fraca",
  "Queda de neve moderada e irregular",
  "Queda de neve moderada",
  "Queda de neve forte e irregular",
  "Neve intensa",
  "Granizo",
  "Aguaceiros fracos",
  "Aguaceiros moderados ou fortes",
  "Aguaceiros fracos com neve",
  "Aguaceiros moderados ou fortes com neve",
  "Aguaceiros fracos com granizo",
  "Aguaceiros moderados ou fortes com granizo",
  "Chuva torrencial",
  "Possibilidade de trovoada",
  "Chuva fraca irregular com trovoada",
  "Chuva moderada ou forte com trovoada",
  "Neve fraca irregular com trovoada",
  "Neve moderada ou forte com trovoada",
]

